# Generated by Django 4.2.7 on 2024-01-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.FloatField(max_length=15, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customer_profile_pics/')),
            ],
        ),
    ]
